name: Test
on:
  push:
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        # run: kk
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
